---
- name: Playbook to install Firefox
  hosts: ubuntu
  become: true
  tasks:

  - name: Ansible apt install snapd
    apt:
      name: snapd
      state: latest

  - name: Ansible start snapd.socket
    systemd:
      name: snapd.socket
      state: started

  - name: Ansible snap install firefox
    snap:
      name:
        - firefox
